pipeline:
  identifier: Build_shaurya_harness_Simple_Node_App_1701162015992
  name: Build Node
  orgIdentifier: default
  projectIdentifier: CIEHackathonYAMLGen
  properties:
    ci:
      codebase:
        connectorRef: skgithub
        repoName: shaurya-harness/Simple-Node-App
        build: <+input>
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: npminstall
                  name: npm_install
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
              - step:
                  identifier: npmtest
                  name: npm_test
                  spec:
                    shell: Sh
                    command: npm run test:junit -- --outputDirectory=./harness --outputName=test-report.xml
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - "**/report.xml"
                  timeout: ""
                  type: Run
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    image: plugins/docker
                    settings:
                      dry_run: "true"
                      repo: hello/world
                      tags: latest
                  timeout: ""
                  type: Plugin
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: jtdock
                    repo: smjth/testnode
                    tags:
                      - latest
                    caching: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
